# -*- coding: utf-8 -*-
"""Teslagi_Sesi1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KUl93jzxpKgoAng72phHRH5TsDvx6j9C
"""

print(12459657859783783-1)

print(123456789-2+2)

print(5)
print(type(5))

print(4.2)
print(type(4.2))

print(4.)
print(type(4.))

print(.4)
print(type(.4))

print(.4E3)

print(4E3)

print(4.e3)

print(4.e-3)

print(4.e+3)

print(.4e+3)

print('temonilo')
print(type('temonilo'))

print(type(True))

print(type(False))

a=500
print(a)

a

a=500
a
a=600
a

n='temonilo'
n

a=b=c=400
a, b, c

a=b=c!=400
a, b, c

a=b=c!=400
print(c)

a=b=c!=400
print(a,b,c)

var = 'temonilo'
print(var)

var = 20.00002
print(var)

nama = 'temonilo'
umur =1.5
laki-laki = True
print(nama, umur, laki-laki)

nama = 'temonilo'
umur =1.5
laki_laki = True
print(nama, umur, laki_laki)

nama = 'temonilo'
umur =1.5
lakilaki = True
print(nama, umur, lakilaki)

1-laki = false

age = 1
Age = 2
aGe = 3
AGE = 4
a_g_e = 5
_age = 6
age_ = 7
_AGE_ = 8

print(age, Age, aGe, AGE, a_g_e, _age, age_, _AGE_)

a = 10
b = 20
print(a+b)
a+b
a + b

a = 10
b = 20
a + b - 5

a=450
b=90

a+b

a-b

a*b

a/b

a%b

a**b

a = 10
b = 20
print(a == b)
print(a != b)
print(a <= b)
print(a >= b)

s = 'foo'
t = 'bar'
u = 'baz'
print(s + t)
print(s + t + u)
print('Hacktiv8 ' + 'PTP')

temon = 'nilo..'
temon * 10

temon = 1
temon * 74667

temon = 'nilo'
print(temon in "nama anabul saya adalah temonilo")

temon = 'nilo'
print(temon in "nama anabul saya adalah temon")

temon = 'nilo'
print(temon.capitalize())

temon = 'nilo'
print(temon.lower())

temon = 'nilo'
print(temon.title())

temon = 'nilo'
print(temon.upper())

a = ['temon','nilo','anabul','jelek']
print(a)

a = ['temon','nilo','anabul','jelek']
b = ['temon','nilo','anabul','jelek']
print(a==b)
print(a!=b)



a = ['temon','nilo','anabul','jelek']
b = ['temon','nilo','jelek','anabul']
print(a==b)
print(a!=b)

a = [21.42, 'foobar', 3, 4, 'bark', False, 3.14159]
print(a)

a = ['temon','nilo','anabul','jelek']
print(a[0])
print(a[3])

a = ['temon','nilo','anabul','jelek']
print(a[5])

a = ['temon','nilo','anabul','jelek',"sangat"]
print(a[2])

a = ['temon','nilo','anabul','jelek',"sangat"]
print(a[-2])

a = ['temon','nilo','anabul','jelek',"sangat"]
print(a[-5])

a = ['temon','nilo','anabul','jelek',"sangat"]
print(a[1:10])

a = ['temon','nilo','anabul','jelek',"sangat"]
print(a[1:2])

a = ['temon','nilo','anabul','jelek',"sangat"]
print(a[0:3])

a = ['temon','nilo','anabul','jelek',"sangat"]
print(a[0:5])

a = ['temon','nilo','anabul','jelek',"sangat"]
print(a[1:5])

a = ['temon','nilo','anabul','jelek',"sangat"]
print(a+['nakal','selalu'])
print(a*2)

a = ['temon','nilo','anabul','jelek',"sangat"]
print(a+['nakal','selalu']*2)

a = ['temon','nilo','anabul','jelek',"sangat"]
print('panjang=',len(a))

a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(min(a))

a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(max(a))

a = [99, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(max(a))

a = ['temon','nilo','anabul','jelek',"sangat"]
print(a)
a[2] = 8
a[-4] = 'NAKAL'
a[4] = 4
print(a)

a = ['temon','nilo','anabul','jelek',"sangat"]
del a[4]
print(a)

a = ['temon','nilo','anabul','jelek',"sangat"]
print(a[1:4])
a[1:4] = ['a','b','c']
print(a)

a = ['temon','nilo','anabul','jelek',"sangat"]
print(a[1:4])
a[1:4] = [0.2,0.9,0.5]
print(a)

t = ('temon','nilo','anabul','jelek',"sangat")
print(t)
print(t[1])
t[2] = nakal
print(t)

(s1, s2, s3, s4, s5) = ('temon','nilo','anabul','jelek',"sangat")
s2

MLB_team = {'Colorado': 'Rockies',
    'Boston': 'Red Sox',
    'Minnesota': 'Twins',
    'Milwaukee': 'Brewers',
    'Seattle': 'Mariners'}

print(MLB_team['Minnesota'])
print(MLB_team['Colorado'])

MLB_team['Kansas City'] = 'Royals'
MLB_team

MLB_team['Seattle'] = 'Seahawks'
MLB_team

del MLB_team['Seattle']
MLB_team

person = {}
type(person)
person['fname'] = 'Hack'
person['lname'] = 'PTP'
person['age'] = 51
person['spouse'] = 'Edna'
person['children'] = ['Ralph', 'Betty', 'Joey']
person['pets'] = {'dog': 'Fido', 'cat': 'Sox'}

person

print(person['fname'])
print(person['lname'])

print(person['children'])
print(person['children'][1])

print(person['pets'])
print(person['pets']['cat'])

d = {'a': 10, 'b': 20, 'c': 30}

print(d.items())

print(d.keys())

print(d.values())

person1_age = 42
person2_age = 16
person3_age = 71

someone_is_of_working_age = (person1_age >= 18 and person1_age <= 65) or (person2_age >= 18 and person2_age <= 65) or (person3_age >= 18 and person3_age <= 65)
someone_is_of_working_age

someone_is_of_working_age = ((person1_age >= 18 and person1_age <= 65)
    or (person2_age >= 18 and person2_age <= 65)
    or (person3_age >= 18 and person3_age <= 65))

someone_is_of_working_age